name:                servant-client-benches
version:             0.1.0.0
github:              "githubuser/servant-client-benches"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/servant-client-benches#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- bytestring
- connection
- data-default-class
- servant
- servant-server
- servant-client
- servant-http2-client
- http-client
- http-client-tls
- http2
- http2-client
- text
- timeit
- tls
- warp >= 3.2.24
- warp-tls
- exceptions
- mtl
- transformers
- async
- deepseq
- warp-grpc
- http2-client-grpc
- http2-grpc-types
- proto-lens
- proto-lens-protoc
- proto-lens-runtime
- lens
- lens-labels

library:
  source-dirs:
  - src
  - gen

executables:
  servant-client-benches-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - servant-client-benches

tests:
  servant-client-benches-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - servant-client-benches
